command_timeout = 1000
add_newline = false

format = "$username$hostname$directory$git_branch$git_state$git_status$cmd_duration$line_break$character"

[directory]
style = "#71acca"

[character]
success_symbol = "[❯](#deb6bb)"
error_symbol = "[❯](#eb6f92)"
vimcmd_symbol = "[❮](#9ccfd8)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
stashed = "≡"

[git_state]
format = "\\([$state( $progress_current/$progress_total)]($style)\\) "
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"

[hostname]
ssh_only = true
format = "@[$hostname]($style) "
style = "bold green"

[username]
disabled = true
